### ISSUE TITLE
when I try to import fragments and stuff, there's always an error. I tried different solutions but not working 

### ISSUE THREAD

**Issue by ehsandevs** [deiteris/api-contractor#2]
![image](https://user-images.githubusercontent.com/25667150/146675600-27d05424-e535-4459-a455-9e5f8e71852b.png)

![image](https://user-images.githubusercontent.com/25667150/146675616-dbceb53c-619b-475b-9bc0-1b63c6e19d1d.png)

**Comment by deiteris** [comment]
Hi @niamileo. What version are you using? Could you also show your `./traits/hasRequestItem.raml` and `resourceTypes/index.raml` files?

**Comment by deiteris** [comment]
Hi @niamileo. The extension has been updated with a fix. Please update the extension and re-open the issue if it still doesn't work for you.
